name: Python CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      #step1: Check out the code from the repository
      - name: Check out code
        uses: actions/checkout@v2

        # step2: Setup python eviroment
      - name: Set out Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.8"
        # steps3:Install dependencies
      - name: Install dependencies
        run: python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run tests
        run: pytest
